### ISSUE TITLE
Generating `full_version`

### ISSUE THREAD

**Issue by LecrisUT** [LecrisUT/CMakeExtraUtils#24]
This is more nuanced as discussed in the PR. Need to investigate how setuptools_scm calculates it more carefully.

              >> but computing the next M.m.p always seemed iffy -- perhaps scm has conventions nowadays.

> Interesting, can you elaborate. I thought it was just the git describe info directly.

I was referring to `.postN` being distance beyond the most recent tag, which is what one gets from `git describe`. Whereas `.devN` is distance on the way to the _next_ tag, so the versioner software has to make a choice whether that's M+1.0 or M.m+1 or M.m.p+1, etc. I get around this in that psi4 script by having the user commit the intended upcoming tag, but I don't pretend that that's a feature :-) scm might well have conventions on this now -- I just haven't looked into it lately. https://packaging.python.org/en/latest/specifications/version-specifiers/#summary-of-permitted-suffixes-and-relative-ordering (succeeds pep440).

_Originally posted by @loriab in https://github.com/LecrisUT/CMakeExtraUtils/issues/19#issuecomment-1879250048_

**Comment by LecrisUT** [comment]
@loriab I have implemented two versions from [setuptools_scm](https://setuptools-scm.readthedocs.io/en/latest/extending/#available-implementations):
- `DEV == guess-next-dev`
- `POST == post-release`

Care to give some feedback or suggestions on it?

**Comment by loriab** [comment]
Sorry for the delay -- I've been breaking Libint, then hauling it back into working order.

I substituted out the latest DynamicVersion.cmake file today. Below are the two modes, and a fake M.m (no patch) tag ran fine, too. (Ignore the `post999` -- that's a hard-coded string.)

default (dev) mode
```
#   -- LibintRepository_VERSION      2.8.2
#   -- LibintRepository_VERSION_FULL 2.8.2.dev61+g8cb6f56
#   -- LibintRepository_COMMIT       8cb6f56b68af2e1da661acf39c9ce4a086865a8a
#   -- LibintRepository_SHORT_HASH   8cb6f56
#   -- LibintRepository_DISTANCE     61
#   -- LibintRepository_DESCRIBE     v2.8.1-61-g8cb6f56
#   -- LIBINT_GIT_COMMIT         8cb6f56
#   -- LIBINT_VERSION_YEAR       2024
#   -- LIBINT_DESCRIPTION        A library for the evaluation of molecular integrals of many-body operators over Gaussian functions
#   -- Version: Full 2.8.2-post999 Numeric 2.8.2 Sortable 2.8.2.post61
```
post mode
```
#   -- LibintRepository_VERSION      2.8.1
#   -- LibintRepository_VERSION_FULL 2.8.1.post61+g8cb6f56
#   -- LibintRepository_COMMIT       8cb6f56b68af2e1da661acf39c9ce4a086865a8a
#   -- LibintRepository_SHORT_HASH   8cb6f56
#   -- LibintRepository_DISTANCE     61
#   -- LibintRepository_DESCRIBE     v2.8.1-61-g8cb6f56
#   -- LIBINT_GIT_COMMIT         8cb6f56
#   -- LIBINT_VERSION_YEAR       2024
#   -- LIBINT_DESCRIPTION        A library for the evaluation of molecular integrals of many-body operators over Gaussian functions
#   -- Version: Full 2.8.1-post999 Numeric 2.8.1 Sortable 2.8.1.post61
```

I'll stick with post mode for Libint (unless EFV wants to switch) because there are many places that don't allow expressing the the dev/post stuff, and I don't want the next/computed M.m.p part out in the wild w/o its devN modifier. Thanks for the addition!
